# Generated by Django 5.2.5 on 2025-08-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSamsung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('Fk_Compra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetoSamsung.compra')),
                ('Fk_Produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetoSamsung.produto')),
            ],
        ),
    ]
